// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: pkg/api/proto/agent_queue.proto

package agent_queue

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeseminateConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId  string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Config  []byte `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	Webhook string `protobuf:"bytes,3,opt,name=webhook,proto3" json:"webhook,omitempty"`
}

func (x *DeseminateConfigRequest) Reset() {
	*x = DeseminateConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_proto_agent_queue_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeseminateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeseminateConfigRequest) ProtoMessage() {}

func (x *DeseminateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_agent_queue_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeseminateConfigRequest.ProtoReflect.Descriptor instead.
func (*DeseminateConfigRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_agent_queue_proto_rawDescGZIP(), []int{0}
}

func (x *DeseminateConfigRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DeseminateConfigRequest) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *DeseminateConfigRequest) GetWebhook() string {
	if x != nil {
		return x.Webhook
	}
	return ""
}

type DeseminateConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeseminateConfigResponse) Reset() {
	*x = DeseminateConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_proto_agent_queue_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeseminateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeseminateConfigResponse) ProtoMessage() {}

func (x *DeseminateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_agent_queue_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeseminateConfigResponse.ProtoReflect.Descriptor instead.
func (*DeseminateConfigResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_agent_queue_proto_rawDescGZIP(), []int{1}
}

var File_pkg_api_proto_agent_queue_proto protoreflect.FileDescriptor

var file_pkg_api_proto_agent_queue_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0f, 0x43, 0x31, 0x32, 0x53, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x51, 0x75, 0x65,
	0x75, 0x65, 0x22, 0x64, 0x0a, 0x17, 0x44, 0x65, 0x73, 0x65, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x18,
	0x0a, 0x07, 0x77, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x77, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x22, 0x1a, 0x0a, 0x18, 0x44, 0x65, 0x73, 0x65,
	0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x32, 0x75, 0x0a, 0x0a, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x51, 0x75, 0x65,
	0x75, 0x65, 0x12, 0x67, 0x0a, 0x10, 0x44, 0x65, 0x73, 0x65, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x28, 0x2e, 0x43, 0x31, 0x32, 0x53, 0x2e, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x51, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x44, 0x65, 0x73, 0x65, 0x6d, 0x69, 0x6e,
	0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x29, 0x2e, 0x43, 0x31, 0x32, 0x53, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x51, 0x75, 0x65,
	0x75, 0x65, 0x2e, 0x44, 0x65, 0x73, 0x65, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x2e,
	0x2e, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_api_proto_agent_queue_proto_rawDescOnce sync.Once
	file_pkg_api_proto_agent_queue_proto_rawDescData = file_pkg_api_proto_agent_queue_proto_rawDesc
)

func file_pkg_api_proto_agent_queue_proto_rawDescGZIP() []byte {
	file_pkg_api_proto_agent_queue_proto_rawDescOnce.Do(func() {
		file_pkg_api_proto_agent_queue_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_api_proto_agent_queue_proto_rawDescData)
	})
	return file_pkg_api_proto_agent_queue_proto_rawDescData
}

var file_pkg_api_proto_agent_queue_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_api_proto_agent_queue_proto_goTypes = []interface{}{
	(*DeseminateConfigRequest)(nil),  // 0: C12S.AgentQueue.DeseminateConfigRequest
	(*DeseminateConfigResponse)(nil), // 1: C12S.AgentQueue.DeseminateConfigResponse
}
var file_pkg_api_proto_agent_queue_proto_depIdxs = []int32{
	0, // 0: C12S.AgentQueue.AgentQueue.DeseminateConfig:input_type -> C12S.AgentQueue.DeseminateConfigRequest
	1, // 1: C12S.AgentQueue.AgentQueue.DeseminateConfig:output_type -> C12S.AgentQueue.DeseminateConfigResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_api_proto_agent_queue_proto_init() }
func file_pkg_api_proto_agent_queue_proto_init() {
	if File_pkg_api_proto_agent_queue_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_api_proto_agent_queue_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeseminateConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_proto_agent_queue_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeseminateConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_api_proto_agent_queue_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_proto_agent_queue_proto_goTypes,
		DependencyIndexes: file_pkg_api_proto_agent_queue_proto_depIdxs,
		MessageInfos:      file_pkg_api_proto_agent_queue_proto_msgTypes,
	}.Build()
	File_pkg_api_proto_agent_queue_proto = out.File
	file_pkg_api_proto_agent_queue_proto_rawDesc = nil
	file_pkg_api_proto_agent_queue_proto_goTypes = nil
	file_pkg_api_proto_agent_queue_proto_depIdxs = nil
}
